// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.file-restriction",
    "name": "File Upload Restriction",
    "description": "Restricts file uploads to specific image types (PNG, JPG, SVG).",
    "homepage_url": "https://github.com/mattermost/mattermost-plugin-starter-template",
    "support_url": "https://github.com/mattermost/mattermost-plugin-starter-template/issues",
    "icon_path": "assets/starter-template-icon.svg",
    "version": "0.0.0+",
    "min_server_version": "6.2.1",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "darwin-arm64": "server/dist/plugin-darwin-arm64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "linux-arm64": "server/dist/plugin-linux-arm64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [],
        "sections": null
    }
}
`);

export default manifest;
